[package]
name = "aenigmix"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type=["lib"]
bench=false

[[bin]]
name="aenigmix"
test=false
bench=false

[dependencies]
